# Generated by Django 4.0.4 on 2022-05-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('decription', models.TextField(default='')),
                ('official_url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WiredMicrophone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('decription', models.TextField(blank=True)),
                ('sku', models.SlugField(max_length=7)),
                ('diameter', models.PositiveSmallIntegerField(default=0)),
                ('length', models.PositiveSmallIntegerField(default=0)),
                ('diaphragm_type', models.CharField(max_length=32)),
                ('polar_pattern', models.CharField(max_length=32)),
                ('polar_pattern_switch', models.BooleanField(default=False)),
                ('on_off_switch', models.BooleanField(default=False)),
                ('require_phantom_power', models.BooleanField(default=False)),
                ('cable_detached', models.BooleanField(default=True)),
                ('connection_type', models.CharField(max_length=16)),
                ('impedance', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(max_length=32)),
                ('manual_url', models.URLField(default='')),
                ('warranty_years', models.PositiveSmallIntegerField(default=2)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
